### PR TITLE
sAlert config can only be called on the client

### PR DESCRIPTION
**Pull request by panphora**
Updated the docs to reflect this

### CODE REVIEW

**Comment by juliancwirko** [comment]
Hey, I think we could only add the information about it without `Meteor.isClient` condition. It is not needed if you place the startup config code in the `client` folder. 
This could be misleading.

**Comment by panphora** [comment]
Okay, I thought it was clearer. It doesn't hurt to do the check on the client, you know?

Anyways, how about removing the word optionally from the docs just above this code? That's really what confused me. Made it seem like maybe it could be configured on the server too. I think it works even better without that anyways.

/nitpick

Great package btw.

**Comment by juliancwirko** [comment]
Ok, do you want to change it here in this PR? Then I will merge it. You can propose your description above this block of code. But we should remove `Meteor.isClient` even if it does not break anything :)
Thanks.

**Comment by panphora** [comment]
I don't know how to modify this pull request. I haven't contributed to many projects and I'm just getting used to it.

I submitted another pull request for the one-word change I suggested :)

I'm closing this one.

**Pull request closed without merging**
